# Generated by Django 4.1.5 on 2023-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Превью')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('date_last_modified', models.DateTimeField(verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
