# Generated by Django 4.1.5 on 2023-01-22 02:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmain_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmain',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blogmain',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='blogmain',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
