SELECT COUNT(DISTINCT CONTACT_NAME)
FROM CUSTOMERS;

SELECT DISTINCT CONCAT(CITY, COUNTRY) AS LIVE_IN
FROM CUSTOMERS;

SELECT CS.COMPANY_NAME, CONCAT(EP.FIRST_NAME, ' ', EP.LAST_NAME) AS FIO
FROM ORDERS ORR
JOIN CUSTOMERS CS USING(CUSTOMER_ID)
JOIN EMPLOYEES EP USING(EMPLOYEE_ID)
JOIN SHIPPERS SH ON ORR.SHIP_VIA = SH.SHIPPER_ID
WHERE 'London' IN (CS.CITY, EP.CITY) AND SH.COMPANY_NAME = 'Speedy Express';

SELECT CONTACT_NAME, NULL AS ORDER_ID
FROM CUSTOMERS
WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM ORDERS)