SELECT * FROM ORDERS
ORDER BY required_date, SHIPPED_DATE

SELECT AVG(REQUIRED_DATE - SHIPPED_DATE)
FROM ORDERS
WHERE SHIP_COUNTRY = 'USA'

SELECT SUM(UNIT_PRICE * UNITS_IN_STOCK)
FROM PRODUCTS
WHERE DISCONTINUED > 0