SELECT PD.PRODUCT_NAME, UNITS_ON_ORDER, SP.CONTACT, SP.PHONE
FROM PRODUCTS PD
JOIN CATEGORIES CT USING(CATEGORY_ID)
JOIN SUPPLIERS SP ON PD.PRODUCT_NAME = SP.PRODUCT
WHERE PD.DISCONTINUED > 0 AND CT.CATEGORY_NAME IN ('Beverages', 'Seafood') AND PD.UNITS_ON_ORDER < 20

